let localCity=[

    {
        title: "Jewellery World Exhibition",
        description: "A premier jewellery showcase featuring traditional and contemporary designs across gold, silver, diamonds, and gemstones. Live demonstrations by artisans. Free entry for public and trade professionals.",
        image: "https://media.insider.in/image/upload/c_crop,g_custom/v1745672235/iip4qclijctpxzgqopfw.jpg",
        date: "July 11–13, 2025 (Note: slightly overlaps)",
        location: "YMCA International Centre, Makarba, Ahmedabad",
        time: "10:00 AM – 6:00 PM daily",
        city: "Ahmedabad",
    },
    {
        title: "JALSA Designer & Lifestyle Exhibition",
        description: "Exhibition showcasing designer wear, artisan crafts, fashion and lifestyle products.",
        image: "https://www.eventsgram.in/images/users/1678171501.jpg",
        date: "July 18–20, 2025",
        location: "Seema Hall, Satellite, Ahmedabad",
        time: "11;00  AM–8: 00  PM",
        city: "Ahmedabad",

    },
    {
        title: "Bridal Asia – The Symphony of Jewels",
        description: "Prestigious wedding exhibition featuring bridal wear designers, jewellery, caterers, photographers and other wedding planners.",
        image: "https://i.pinimg.com/736x/40/6e/53/406e53b2b98eea3e50dbbbf71f11c0f4.jpg",
        date: "July 25–26, 2025",
        location: "Jade Luxury Banquets, Ahmedabad",
        time: "10:00 AM – 6:00 PM",
        city: "Ahmedabad",

    },
    {
        title: "Rath Yatra (Ahmedabad)",
        description: "Major annual chariot procession of Lord Jagannath, Balrama and Subhadra. Involves rituals at 4 AM followed by ~7 AM parade through city.",
        image: "https://tse4.mm.bing.net/th?id=OIF.siwMXnMDlP4tvjg%2bGgBZIQ&pid=Api&P=0&h=180",
        date: "As per Ashadha Sud Bij (mid‑July; confirm exact Gujarati calendar date)",
        location: "Starts at Jagannath Temple, Jamalpur; route ~14 km across city",
        time: "Mangla Aarti at 4:00 AM, procession begins ~7:00 AM",
        city: "Ahmedabad",

    },
    {
        title: "Culture Camp 2025 @ Bhilai",
        description: "A cultural and spiritual retreat by Hare Krishna Movement with sessions on Vedic arts, lifestyle, and meditation.",
        image: "https://i.ytimg.com/vi/sB8bMMV8rqU/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGHIgQShYMA8=&rs=AOn4CLDiFtcUhUS--p9zzlI-rKfUJpliQA",
        date: "July 2025 (Exact dates to be confirmed)",
        location: "ISKCON Bhilai Campus or Bhilai–Raipur Zone",
        time: "Session-wise schedule",
        city: "Bhilai",

    },
    {
        title: "QCFI Bhilai Chapter Convention on Integrated Safety Circle",
        description: "A technical convention focusing on quality circles, safety awareness, and best industrial practices.",
        image: "https://www.qcfibhilai.in/Images/quick/head.jpg",
        date: "6 July 2025",
        location: "Shri Shankaracharya Technical Campus, Bhilai",
        time: "9:00 AM – 6:00 PM",
        city: "Bhilai",
    },
    {
        title: "Ethnic Night 2025 @ IIT Bhilai",
        description: "An annual cultural celebration featuring traditional dance, folk songs, and ethnic attire organized by IIT Bhilai students.",
        image: "https://images.shiksha.com/mediadata/images/articles/1697799491phpaCn11D.jpeg",
        date: "July 2025 (Exact date to be announced)",
        location: "IIT Bhilai Campus",
        time: "6:00 PM onwards",
        city: "Bhilai",
    },
    {
        title: "Panditani Folk Showcase – Tribal Arts of Chhattisgarh",
        description: "Live showcase of folk storytelling, music, and tribal dance celebrating local cultural legends like Teejan Bai.",
        image: "https://im.hunt.in/cg/Chhatis/About/Profile/Culture/fgfd.jpg",
        date: "20 July 2025 (Tentative)",
        location: "Chhattisgarh Cultural Auditorium, Bhilai",
        time: "6:00 PM – 8:00 PM",
        city: "Bhilai",
    },
    {
        title: "Jama Masjid Open-Audio Evening",
        description: "Spiritual community gathering with live Sufi or devotional music held in the mosque courtyard.",
        image: "Jama Masjid Open-Audio Evening",
        date: "July 2025 (Based on community schedule)",
        location: "Jama Masjid, Sector 6, Bhilai",
        time: "7:00 PM onwards",
        city: "Bhilai",
    },
    {
        title: "Bhavanubhava Dance Festival", 
        description: "An annual classical dance festival featuring performances like Bharatanatyam, Kathak, Mohiniyattam, and dance dramas at Bharat Bhavan.",
        image: "https://tse3.mm.bing.net/th?id=OIP.s3DMJmS5T7BEQAP2AktGPwHaE0&pid=Api&P=0&h=180",
        date: "1–4 August 2025",
        location: "Bharat Bhavan, Shymala Hills",
        time: "7:00 PM – 12:00 AM",
        city: "Bhopal",
    },
    {
        title: "Technosearch – MANIT Bhopal Tech Fest",
        description: "Annual technical & cultural festival with workshops, seminars, competitions and evening ProNites.",
        image: "https://tse1.mm.bing.net/th?id=OIP.e3e6kfag5RK1bRScavhcowHaDt&pid=Api&P=0&h=180",
        date: "October 2025 (Exact dates TBC)",
        location: "MANIT Bhopal Campus",
        time: "Varies by event",
        city: "Bhopal",

    },
    {
        title: "Month‑long Cultural Festival",
        description: "A vibrant cultural series featuring plays, qawwali, Haryanvi dance & drama, comedy shows at the Open Air Theatre.",
        image: "https://images.hindustantimes.com/rf/image_size_640x362/HT/p2/2016/06/30/Pictures/_dd4e49b6-3eb2-11e6-974a-2ab7ab59b8ea.jpg",
        date: "2 July, 9 July, 16 July, 23 July, 30 July 2025",
        location: "Open Air Theatre, Sector‑29, Gurgaon",
        time: "7:30 PM",
        city: "Gurgaon",
    },
    {
        title: "Paragliding Experience Gurgaon",
        description: "Adventure paragliding session over the Aravali hills – early morning scenic flights.",
        image: "https://tse2.mm.bing.net/th?id=OIP.9FmI4Y2wo2DckcjR44GVEwHaEc&pid=Api&P=0&h=180",
        date: "18 July 2025",
        location: "Rush To Fly, outskirts of Gurgaon",
        time: "7:00 AM",
        city: "Gurgaon",

    },
    {
        title: "Prateek Kuhad Silhouettes Tour – Gurgaon",
        description: "Acoustic evening with singer‑songwriter Prateek Kuhad performing his popular tracks live.",
        image: "https://tse4.mm.bing.net/th?id=OIP.iUtQpMtfToDHVUmEDWa9DgHaDt&pid=Api&P=0&h=180",
        date: "2025 (exact date TBC)",
        location: "Various venues, Gurgaon",
        time: "Evening (time TBC)",
        city: "Gurgaon",

    },
    {
        title: "Outdoor Star‑Gazing Meetup",
        description: "Community-organized telescope star-gazing event on Gurgaon outskirts, near farmland.",
        image: "https://tse1.mm.bing.net/th?id=OIP.3tSNzSCC9iQ2EhOj8Y9ZlgHaFb&pid=Api&P=0&h=180",
        date: "Various dates, 2025 (check group listings)",
        location: "Farmland outskirts of Gurgaon",
        time: "Evenings",
        city: "Gurgaon",

    },
    {
        title: "IREX Residency & Citizenship Conclave",
        description: "An international real-estate and immigration investment show with participation from global countries.",
        image: "https://www.eventalways.com/media/eventlogo/large/undefined-logo-1684753912.jpg",
        date: "18–19 July 2025",
        location: "Trident Hotel, HITEC City Main Road, Hyderabad",
        time: "Daytime (exact timing TBC)",
        city: "Hyderabad",

    },
    {
        title: "Smart CIO Summit 2025",
        description: "A conference for IT leaders covering strategic insights and best practices in technology, cybersecurity, and leadership.",
        image: "https://tse3.mm.bing.net/th?id=OIP.I-uZxJDhoHPgHVGqly1ijgHaC-&pid=Api&P=0&h=180",
        date: "24 July 2025",
        location: "Hyderabad (venue TBC)",
        time: "Daytime",
        city: "Hyderabad",

    },
    {
        title: "FLO Hyderabad Style Tatva 2025",
        description: "Fashion and lifestyle exhibition featuring designer wear, jewellery, beauty products and lifestyle pop-ups.",
        image: "https://tse3.mm.bing.net/th?id=OIP.HynfgnsJiHla3kTzk6t8sgAAAA&pid=Api&P=0&h=180",
        date: "1–31 July 2025",
        location: "HITEX Convention Centre, Hyderabad",
        time: "11:00 AM – 8:00 PM",
        city: "Hyderabad",

    },
    {
        title: "Hyderabad Dental Show 2025",
        description: "A professional expo showcasing the latest in dental equipment, technology and services.",
        image: "https://www.dentee.com/educate/program/getimage?imageName=0a185eb3-9782-4075-ba5d-f2b83a062241hyderabaddentalshow.jpg&imagefolderGuid=6a33c688-ae23-4f57-b6cb-83cbdabbd541",
        date: "1–31 July 2025",
        location: "HITEX Convention Centre, Hyderabad",
        time: "11:00 AM – 8:00 PM",
        city: "Hyderabad",

    },
    {
        title: "Ghoomar Mahotsav",
        description: "Cultural celebration organised by Jaipur Moms featuring folk performance of Ghoomar dance.",
        image: "https://i.ytimg.com/vi/FHF-uxs697g/maxresdefault.jpg",
        date: "16 July 2025",
        location: "C‑Scheme Marg, Ashok Nagar, Jaipur",
        time: "5:00 PM",
        city: "Jaipur",

    },
    {
        title: "Dunes Techno Assembly Jaipur Edition 2",
        description: "A techno music festival featuring some of the most popular and trending artists in underground music.",
        image: "https://media.insider.in/image/upload/c_crop,g_custom/v1656920428/tjpxsoeiuslxkkmbjn36.jpg",
        date: "16 July 2025",
        location: "Bhanwar Singh Palace, Jaipur",
        time: "6:00 PM",
        city: "Jaipur",

    },
    {
        title: "IndianOil Durand Cup Football Matches",
        description: "Action-packed football matches as part of Asia’s oldest tournament, featuring Jamshedpur’s home games at JRD Tata Sports Complex.",
        image: "https://i.ytimg.com/vi/R8kwscHh8hQ/maxresdefault.jpg",
        date: "22 July – 24 August 2025",
        location: "JRD Tata Sports Complex, Bistupur, Jamshedpur",
        time: "Match-specific timings (day & evening fixtures)",
        city: "Jamshedpur",

    },
    {
        title: "Premium Festive Fashion Exhibition",
        description: "Indoor lifestyle and fashion expo featuring stalls for art, handicrafts, clothing, jewellery, food, and more; free entry.",
        image: "https://www.eventsgram.in/images/event-img/211746694059b.png",
        date: "22–23 July 2025",
        location: "Hotel Shree Ram International, Residency Road, Jodhpur",
        time: "11:00 AM – 8:00 PM",
        city: "Jodhpur",

    },
    {
        title: "Rao Jodha Desert Rock Park Guided Walk",
        description: "Monsoon-time guided nature walk exploring restored desert flora on volcanic rock trails near Mehrangarh Fort.",
        image: "https://tse3.mm.bing.net/th?id=OIP.Ku8tYLAzOvoRg3L31s8P1gHaEK&pid=Api&P=0&h=180",
        date: "Daily (16–31 July 2025)",
        location: "Rao Jodha Desert Rock Park, near Mehrangarh Fort",
        time: "7:00 AM – 6:30 PM",
        city: "Jodhpur",

    },
    {
        title: "Kaylana Lake Evening Excursions",
        description: "Scenic visits to the lakeside with monsoon ambience—ideal for birdwatching and sunset walks.",
        image: "https://i.ytimg.com/vi/XcCQExEVXWE/maxresdefault.jpg",
        date: "Daily (16–31 July 2025)",
        location: "Kaylana Lake, ~8 km NW of city centre",
        time: "Evenings (~6:00 PM – 8:00 PM)",
        city: "Jodhpur",

    },
    {
        title: "Mehrangarh Fort Night Tour",
        description: "After‑hours cultural tour with fort illumination, storytelling, and occasional folk performances under the stars.",
        image: "https://wallpapers.com/images/hd/mehrangarh-fort-night-illumination-wpfvd1tyztokc8an.jpg",
        date: "Selected days (16–31 July 2025)",
        location: "Mehrangarh Fort, Jodhpur",
        time: "Evening/night (times TBC)",
        city: "Jodhpur",
    },
    {
     
        title: "Monsoon Camel Safari in Thar Desert",
        description: "Guided camel treks through rejuvenated dunes with monsoon-coloured vistas just outside Jodhpur.",
        image: "https://img.freepik.com/premium-photo/camel-safari-thar-desert-jaisalmer_78361-18896.jpg",
        date: "Available daily (16–31 July 2025)",
        location: "Thar Desert outskirts (book via local operators)",
        time: "Early morning (~6:00 AM) or late afternoon (~4:00 PM)",
        city: "Jodhpur",

    },
    {
        title: "Mandore Gardens Twilight Walk",
        description: "Evening stroll through historic cenotaphs and gardens brought alive by lush monsoon greenery.",
        image: "https://jodhpurtourism.in/images/places-to-visit/headers/mandore-gardens-jodhpur-entry-fee-timings-holidays-reviews-header.jpg",
        date: "Daily (16–31 July 2025)",
        location: "Mandore Gardens, ~9 km from centre",
        time: "Evening (~5:30 PM – 7:30 PM)",
        city: "Jodhpur",

    },
    {
        title: "IKAAI – Teej & Rakhi Edit",
        description: "Festive-shopping exhibition featuring fashion, accessories, jewellery, and lifestyle pop-ups for Teej and Rakhi celebrations.",
        image: "https://nowlucknow.com/wp-content/uploads/2023/07/collage3-1-1024x683.jpg",
        date: "23 July 2025",
        location: "Landmark Towers, Parade, Kanpur",
        time: "11:00 AM – 8:00 PM",
        city: "Kanpur",

    },
    {
        title: "BookMafiyas Dream Book Fair",
        description: "Huge book fair selling over 500,000 books across 20+ genres—books priced by weight; free entry.",
        image: "https://tse1.mm.bing.net/th?id=OIP.5eFDzO-DVe4GDm7yLNBDRQHaHa&pid=Api&P=0&h=180",
        date: "25–28 July 2025",
        location: "Narula Convention Centre & Rooms, GT Road, Ashok Nagar, Harsh Nagar",
        time: "11:00 AM – 8:00 PM",
        city: "Kanpur",

    },
    {
        title: "Interior & Architecture Design Show",
        description: "Exhibition featuring latest trends in interior design and architecture, with exhibitor stalls and networking opportunities.",
        image: "https://tse2.mm.bing.net/th?id=OIP.h0Y3AOe-uofpVaIiXjh3-AHaFj&pid=Api&P=0&h=180",
        date: "27–28 July 2025",
        location: "Kingston Resort, The Mall, Kanpur",
        time: "11:00 AM – 8:00 PM",
        city: "Kanpur",

    },
    {
        title: "Summer Festival at Central Park",
        description: "Outdoor music, food stalls, games and community fun at Central Park to celebrate monsoon vibes.",
        image: "https://www.centralparkfestival.nl/uploads/images/archief2023/230617_1738_centralpark_bobbiephotography_021_lrwm.jpg",
        date: "25 July 2025",
        location: "Central Park, Shastri Nagar, Kanpur",
        time: "5:00 PM onwards",
        city: "Kanpur",

    },
    {
        title: "SAN 2025 – 'Story of Blood & Books' Stage Play",
        description: "Live theatre performance written by Piyush Mishra—a dramatic stage play held in Kanpur Civic Lines.",
        image: "https://www.mumbaitheatreguide.com/dramas/hindi/images/san-2025-story-of-blood-books.jpg",
        date: "23 July 2025",
        location: "Merchants' Chamber of Uttar Pradesh, Civil Lines, Kanpur",
        time: "8:00 PM",
        city: "Kanpur",

    },
    {
        title: "Abhilash Walia Live Stand-up Comedy",
        description: "Live comedy show by YouTube sensation and Great Indian Laughter Challenge winner Abhilash Walia.",
        image: "https://tse3.mm.bing.net/th?id=OIP.1MZUOq-6EXrocxhU8qgkaAHaDt&pid=Api&P=0&h=180",
        date: "28 July 2025",
        location: "Pizza Central, Lakhanpur, Khyora, Kanpur",
        time: "6:30 PM",
        city: "Kanpur",

    },
    {
        title: "KSINC Monsoon Cruise Packages",
        description: "Discounted sheltered-backwaters cruise trips (e.g., Sagararani) highlighting monsoon scenery around Mattancherry & Willingdon Island.",
        image: "https://mycruise.kerala.gov.in:7001/media/Package/471120738_2019-04-03_04-02-23_e82405e62f52.jpeg",
        date: "Daily, 16–31 July 2025",
        location: "Mattancherry / Willingdon Island, Kochi",
        time: "Scheduled daytime slots (check KSINC website)",
        city: "Kochi",

    },
    {
        title: "Kochi Water Metro Sightseeing Rides",
        description: "Electric ferry rides along water‑metro routes—Vyttila–High Court, Fort Kochi feeder lines—ideal for scenic travel.",
        image: "https://tse2.mm.bing.net/th?id=OIP.JQpdwT7yFUYY93ueDdtBHQHaEK&pid=Api&P=0&h=180",
        date: "Daily, 16–31 July 2025",
        location: "Terminals like Vyttila, Fort Kochi, High Court, etc.",
        time: "10 AM – 8 PM (regular service hours)",
        city: "Kochi",

    },
    {
        title: "Marine Drive Monsoon Walks",
        description: "Promenade strolls along APJ Abdul Kalam Marg—viewing Rainbow Bridge, fishing nets, lakeside breeze.",
        image: "https://tse4.mm.bing.net/th?id=OIP.wiguubMfhfvJYXM8hZyg1QHaD8&pid=Api&P=0&h=180",
        date: "Daily, 16–31 July 2025",
        location: "Marine Drive walkway, Ernakulam, Kochi",
        time: "Evenings (~5:30 PM – 7:30 PM)",
        city: "Kochi",

    },
    {
        title: "Local Pop‑Up Art & Craft Markets",
        description: "Weekend stalls and pop‑up artisan markets at mall lobbies (e.g. LuLu Mall, Oberon) featuring crafts, snacks & music.",
        image: "N/A",
        date: "Saturdays & Sundays, 16–31 July 2025",
        location: "LuLu Mall / Oberon Mall, Kochi",
        time: "11 AM – 8 PM",
        city: "Kochi",

    },
    {
        title: "Monsoon Photography Walks",
        description: "Community-led photo walks capturing Kerala’s monsoon life—fishing nets, backwaters, heritage architecture.",
        image: "https://www.oyorooms.com/travel-guide/wp-content/uploads/2019/09/shutterstock_787033735.jpg",
        date: "Weekly evening meetups (16–31 July 2025)",
        location: "Fort Kochi / Marine Drive / Backwaters",
        time: "Evening (~5:00 PM – 7:00 PM)",
        city: "Kochi",
        
    },
    {
        title: "Bharat Pro Sound & Light Expo 2025",
        description: "A professional trade expo showcasing audio, lighting, audiovisual, studio recording & broadcast media technologies.",
        image: "https://tse4.mm.bing.net/th?id=OIP.nKiWLI6bqCLuxMDEjRtupgAAAA&pid=Api&P=0&h=180",
        date: "19–21 July 2025",
        location: "Biswa Bangla Mela Prangan, Kolkata",
        time: "10:00 AM – 6:00 PM",
        city: "Kolkata",

    },
    {
        title: "Kolkata Couture Expo 2025",
        description: "Premier ethnic‑fashion exhibition featuring designer sarees, lehengas, jewellery and bridal ensembles.",
        image: "https://tse4.mm.bing.net/th?id=OIP.KyqQmLXLI_aR-f3SRW3YRwAAAA&pid=Api&P=0&h=180",
        date: "24–26 July 2025",
        location: "Milan Mela Exhibition Complex, Kolkata",
        time: "11:00 AM – 8:00 PM",
        city: "Kolkata",

    },
    {
        title: "Teej & Rakhi Special Exhibition",
        description: "Festive lifestyle exhibition showcasing Teej & Rakhi-themed apparel, accessories, gifting items & décor.",
        image: "https://www.eventsgram.in/images/event-img/2641747473262b.png",
        date: "21–23 July 2025",
        location: "Haldiram Banquets, Ballygunge Park, Kolkata",
        time: "11:00 AM – 8:00 PM",
        city: "Kolkata",

    },
    {
        title: "TMC Martyrs’ Day Rally",
        description: "Trinamool Congress’ large public rally ahead of 2026 Assembly polls, with anticipated record turnout.",
        image:  "https://tse3.mm.bing.net/th?id=OIP.zAKN2uiwBdvq2uiI9V3s4AHaEM&pid=Api&P=0&h=180",
        date: "21 July 2025",
        location: "Multiple Bhowanipore-area venues, Kolkata",
        time: "Morning–Afternoon (exact time TBC)",
        city: "Kolkata",

    },
    {
        title: "Forgotten Histories – History Appreciation Course",
        description: "Two-part course on South Asian history topics (Ashoka, Indus Valley, Gandhi, agrarian movements).",
        image: "https://www.canninghouse.org/storage/uploads/events/2021-events/02-february/1102-forgotten-histories/banner-noinfo_mzfav.png",
        date: "12 & 26 July 2025",
        location: "Kolkata Centre for Creativity, Kolkata",
        time: "11:00 AM – 1:00 PM",
        city: "Kolkata",

    },
    {
        title: "Kishore Sagar Lake Boating & Jag Mandir Visit",
        description: "Enjoy monsoon-time boat rides to Jag Mandir Palace island and stroll along the scenic lakeside with lush surroundings.",
        image: "https://tse4.mm.bing.net/th?id=OIP.4wZSkoBI-dgC0tSysklqFgHaEK&pid=Api&P=0&h=180",
        date: "Daily, 16–31 July 2025",
        location: "Kishore Sagar Talab & Jag Mandir Palace, Kota",
        time: "10:00 AM – 6:00 PM (boat timings)",
        city: "Kota",

    },
    {
        title: "Seven Wonders Park Evening Visit",
        description: "Explore miniature replicas of global monuments, enjoy landscaped lawns and food stalls during monsoon-lit evenings.",
        image: "https://ebnw.net/wp-content/uploads/2021/01/Seven-Wonders-Park-1024x576.jpg",
        date: "Daily, 16–31 July 2025",
        location: "Seven Wonders Park, near Kishore Sagar Lake, Kota",
        time: "4:30 PM – 10:00 PM",
        city: "Kota",

    },
    {
        title: "Chambal Garden & Boat Safari",
        description: "Stroll through the riverside garden and take a Chambal River safari to spot gharials, migratory birds and riverine wildlife.",
        image: "/https://tse2.mm.bing.net/th?id=OIP.yZ87AAKH4ztn9oMH8qlSlwAAAA&pid=Api&P=0&h=180",
        date: "Daily, 16–31 July 2025",
        location: "Chambal Garden & Chambal River jetty, Kota",
        time: "9:00 AM – 6:00 PM",
        city: "Kota",

    },
    {
        title: "Garadia Mahadev Temple & Chambal Gorge Visit",
        description: "Monsoon excursion to Garadia Mahadev perched atop a gorge — enjoy dramatic river views and lush greenery.",
        image: "/https://i.ytimg.com/vi/DlOU622VnNY/maxresdefault.jpg",
        date: "Daily, 16–31 July 2025",
        location: "Garadia Mahadev Temple, Chambal gorge outskirts, Kota",
        time: "Sunrise & sunset visits (plan ahead)",
        city: "Kota",

    },
    {
        
        title: "Kota Fortified Old City Heritage Walk",
        description: "Self-guided heritage walk through old bastions, painted gates, bazaars and colonial-era architecture.",
        image: "https://tse3.mm.bing.net/th?id=OIP.qEVyoAMMVt2wT2kRb_m_twHaD0&pid=Api&P=0&h=180",
        date: "Daily, 16–31 July 2025",
        location: "Rampura, Bajajkhana & Patanpole area, old Kota",
        time: "8:00 AM – 12:00 PM or 4:00 PM – 7:00 PM",
        city: "Kota",

    },
    {
        title: "BOUTIQUE & WEDDING EXPO – July 2025 Lucknow Edition",
        description: "Fashion, lifestyle & jewellery exhibition ahead of Rakhi festival—ideal for designers, brands, and festive shoppers.",
        image: "https://tse1.mm.bing.net/th?id=OIP.AI9hSn0RcZVblbXPFTSR6QHaGO&pid=Api&P=0&h=180",
        date: "19–20 July 2025",
        location: "Hyatt Regency, Gomti Nagar, Lucknow",
        time: "11:00 AM – 8:00 PM (approx.)",
        city: "Lucknow",

    },
    {
        title: "Lucknow Mega Beauty Expo Season 2",
        description: "Large beauty & lifestyle expo with 40+ stalls, live stage demos, celebrity appearances & an award show.",
        image: "https://miro.medium.com/v2/resize:fit:1358/1*YjZj7QAQC7cu3mN3wzW9Aw.jpeg",
        date: "30–31 July 2025",
        location: "Dayal Gateway, Kisan Bazar, Vibhuti Khand, Gomti Nagar",
        time: "10:00 AM – 6:00 PM",
        city: "Lucknow",

    },
    {
        title: "Spices Conference & Expo",
        description: "Trade expo focusing on spice industry—processing, packaging, trade opportunities & networking.",
        image: "https://www.industrialmeeting.club/wp-content/uploads/2024/02/Spices-Herbs-Global-Expo-lr.jpg",
        date: "31 July 2025",
        location: "Udyan Bhawan, Lucknow",
        time: "10:00 AM – 5:00 PM",
        city: "Lucknow",

    },
    {
        title: "Hariyali Teej Festival",
        description: "Traditional Teej celebrations honoring Goddess Parvati–Shiva, with processions, folk music, and rituals.",
        image: "https://img.freepik.com/premium-vector/hariyali-teej-indian-festival-banner-design-template_262129-12270.jpg",
        date: "31 July 2025",
        location: "Various temples & community pandals across Lucknow",
        time: "Morning & evening cultural gatherings",
        city: "Lucknow",

    },
    {
        title: "Gomti Riverfront Musical Fountain & Evening Strolls",
        description: "Daily illuminated fountain shows set to music—perfect for monsoon-time evening walks and relaxation.",
        image: "https://i.ytimg.com/vi/1XvLMIBajFc/maxresdefault.jpg",
        date: "Daily, 16–31 July 2025",
        location: "Gomti Riverfront Park, Lucknow",
        time: "Evenings (~6:30 PM – 9:00 PM)",
        city: "Lucknow",

    },
    {
        title: "Heritage Walk & Tour – Bara Imambara & Bhul Bhulaiya",
        description: "Guided visits to Bara Imambara, exploring the Bhul Bhulaiya maze and historic Rumi Darwaza during monsoon charm.",
        image: "https://lucknowtourism.co.in/images/places-to-visit/header/bara-imambara-lucknow-tourism-entry-fee-timings-holidays-reviews-header.jpg",
        date: "Daily, 16–31 July 2025",
        location: "Bara Imambara, Lucknow",
        time: "10:00 AM – 5:00 PM",
        city: "Lucknow",

    },
    {
        title: "Travel & Tourism Fair (TTF) – Patna 2025",
        description: "India’s premier travel expo featuring exhibitors from 26 countries and states; ideal for travel professionals and enthusiasts.",
        image: "https://www.tradefairdates.com/logos/ttf_logo_6779.jpg",
        date: "19–20 July 2025",
        location: "Samrat Ashok Convention Centre (Gyan Bhawan), Patna",
        time: "10:00 AM – 6:00 PM",
        city: "Patna",

    },
    {
        title: "Fashionista Fashion & Lifestyle Exhibition",
        description: "Lifestyle fair offering designer wear, jewellery, accessories, and more—free entry exhibition.",
        image: "https://cdn.citywoofer.com/events/large/76ghH6Lb5Z_1730702605966.jpg",
        date: "29–30 July 2025",
        location: "Hotel Maurya Patna",
        time: "11:00 AM – 9:00 PM",
        city: "Patna",

    },
    {
        title: "Indira Gandhi Planetarium – Daily Sky Shows",
        description: "Immersive digital astronomy shows and exhibitions featuring modern ZEISS projection, suitable for families and students.",
        image: "https://tse1.mm.bing.net/th?id=OIP.HZdXcBnqd2mK-gjcBZXswAHaE8&pid=Api&P=0&h=180",
        date: "Daily, 16–31 July 2025",
        location: "Indira Gandhi Planetarium, Science Complex, Patna",
        time: "Multiple daily shows (check schedule)",
        city: "Patna",

    },
    {
        title: "Laser Light Show – Buddha Smriti Park",
        description: "Evening laser show highlighting Bihar’s history from Ramayana to modern times (subject to monsoon schedule).",
        image: "https://i.ytimg.com/vi/b83LSAKy58k/hqdefault.jpg",
        date: "Evenings, 16–31 July 2025",
        location: "Buddha Smriti Park, Patliputra, Patna",
        time: "Evenings (usually 6–7 PM)",
        city: "Patna",

    },
    {
        title: "Weekend Pop-up Artisan & Tech Markets",
        description: "Weekend lifestyle pop-ups featuring local crafts, food stalls, science‑tech demos near Bihar Museum or eco‑venues.",
        image: "https://south78.id/wp-content/uploads/2022/12/IMG_8057-scaled.jpg",
        date: "Weekends, 19–20 & 26–27 July 2025",
        location: "Bihar Museum / adjacent lawns, Patna",
        time: "11:00 AM – 7:00 PM",
        city: "Patna",
    },
    {
        title: "Fashionista Nashik 2025",
        description: "First‑edition fashion & lifestyle trade show showcasing designer wear, accessories, cosmetics, home furnishings with ~50 exhibitors.",
        image: "https://tse1.mm.bing.net/th?id=OIP.kLFsLfOTYBnDyDjT4UpojQAAAA&pid=Api&P=0&h=180",
        date: "21–23 July 2025",
        location: "Hotel Emerald Park, Trimbak Road, Nashik",
        time: "10:00 AM – 8:00 PM",
        city: "Nashik",
    },
    {
  
        title: "Premium Festive Edition Exhibition",
        description: "Festive-themed shopping exhibition featuring fashion, jewellery, décor, food stalls at Emerald Park.",
        image: "https://cdn-az.allevents.in/events6/banners/a736af000bb7c18d74a0ee44736589c4ec175fa2e17bacde08aa8dcbee04a261-rimg-w1200-h628-dcffe7d1-gmir?v=1750519476",
        date: "21–23 July 2025",
        location: "Hotel Emerald Park, Trimbak Road, Nashik",
        time: "11:00 AM – 8:00 PM",
        city: "Nashik",
    },
    {
  
        title: "Daily Heritage Visits – Gargoti Museum",
        description: "Explore India’s first gem, mineral & fossil museum with over 1,000 specimens and interactive galleries.",
        image: "https://s7ap1.scene7.com/is/image/incredibleindia/gargoti-museum-nashik-maharashtra-attr-about?qlt=82&ts=1726675357171",
        date: "Daily, 16–31 July 2025",
        location: "Gargoti Museum, Sinnar (≈32 km from Nashik)",
        time: "10:00 AM – 5:00 PM",
        city: "Nashik",
    },
    {
  
        title: "Monsoon Trekking – Satmala Range",
        description: "Guided treks in the Satmala hills (e.g., Dhodap) amid lush Western Ghats scenery and waterfalls.",
        image: "https://tse2.mm.bing.net/th?id=OIP.AKYajI2HzaOMwaPyUzA23AHaE8&pid=Api&P=0&h=180",
        date: "Daily, 16–31 July 2025",
        location: "Satmala Range, Nashik district",
        time: "6:00 AM – 4:00 PM (trek hours)",
        city: "Nashik",
    },
    {
  
        title: "Boat Cruise – Muktidham Temple",
        description: "Monsoon-day visit to the marble temple complex; combine with boat ride on Nashik Road lake.",
        image: "https://tse4.mm.bing.net/th?id=OIP.zDgLPb9-TryE03tUIawpgQHaEo&pid=Api&P=0&h=180",
        date: "Daily, 16–31 July 2025",
        location: "Muktidham Complex, Nashik Road",  
        time: "9:00 AM – 6:00 PM",
        city: "Nashik",
    },
    {
  
        title: "Sunset Strolls & Boat Views",
        description: "Enjoy monsoon sunsets near Godavari river, river‑side walks, glimpse Chinese fishing nets and lakeside ambiance.",
        image: "https://tse4.mm.bing.net/th?id=OIP.EL70zPj9lcCpSkrsNK_CpwHaEK&pid=Api&P=0&h=180",  
        date: "Daily, 16–31 July 2025",
        location: "Godavari Riverfront & Gangapur Road area",
        time: "Evenings (~6:00 PM – 8:00 PM)",
        city: "Nashik",

    },
    {
        title: "NCPA Summer Fiesta Workshops",
        description: "Creative workshops for all ages—including theatre, puppetry, storytelling, dance, comedy and more—offered as part of NCPA’s Summer Fiesta.",
        image: "https://media.insider.in/image/upload/c_crop,g_custom/v1651473959/nztw5puuokkxpnmwatbz.jpg",
        date: "Until 27 July 2025",
        location: "NCPA, Nariman Point, Mumbai",
        time: "Various sessions (daytime)",
        city: "Mumbai",
    },
    {
        title: "Con Brio 2025 – Mini Music Festival",
        description: "A 4-day festival of international and Indian music spanning genres from classical to fusion at NMACC.",
        image: "https://tse3.mm.bing.net/th?id=OIP.1zfYI4lgbt-sTMDtvQAzhgHaE8&pid=Api&P=0&h=180",
        date: "24–27 July 2025",
        location: "NMACC, BKC, Mumbai",
        time: "Evening concerts",
        city: "Mumbai",
    },
    {
        title: "Pottery Date Special @ Dorangos Café",
        description: "Hands-on pottery workshop for beginners and couples, with socializing and clay-sculpting.",
        image: "https://tse4.mm.bing.net/th?id=OIP.NaYb0qJRI3a-lBCV30QyEwHaHa&pid=Api&P=0&h=180",
        date: "Throughout July 2025 (check schedule)",
        location: "Dorangos Café, Bandra, Mumbai",
        time: "Afternoon/evening sessions",
        city: "Mumbai",
    },
    {
        title: "Bandra Station Mahotsav",
        description: "Heritage festival celebrating 160 years of Bandra station with exhibitions, light shows, and competitions.",
        image: "https://images.mid-day.com/images/images/2023/apr/BandraR1_d.jpeg",
        date: "Till 27 July 2025",
        location: "Bandra Station, Mumbai",
        time: "Daytime + Evening Light Shows",
        city: "Mumbai",
    },
    {
        title: "Cultural Evenings at NMACC",
        description: "Art shows, dance, music and exhibitions at Mumbai’s premier cultural centre.",
        image: "https://media.biltrax.com/wp-content/uploads/2023/05/2023-0329-nmacc-night.jpg",
        date: "Selected evenings in July 2025",
        location: "NMACC, Bandra Kurla Complex, Mumbai",
        time: "Evenings",
        city: "Mumbai",
    },
    {
        title: "Study Abroad Expo – IDP",
        description: "Meet top universities from Australia, Canada & NZ to explore admissions and courses.",
        image: "https://i.ytimg.com/vi/AmP0SmleHxU/maxresdefault.jpg",
        date: "20 July 2025",
        location: "Hotel Sheraton Grand, Pune",
        time: "11:00 AM – 4:00 PM",
        city: "Pune",
    },
    {
        title: "Rakhi Special Fashion & Lifestyle Exhibition",
        description: "Festive-themed shopping expo featuring fashion, jewellery, décor and wedding essentials.",
        image: "https://cdn-az.allevents.in/events1/banners/38761c67225ca815dada1df1d016caeb124b24504d0d954a840d8092282cc8ee-rimg-w1200-h629-dcf9ebeb-gmir?v=1716908072",
        date: "27 July 2025",
        location: "Siddhi Banquet, Pune",
        time: "10:00 AM – 9:00 PM",
        city: "Pune",
    },
    {
        title: "International Gifts & Stationery Trade Show",
        description: "Mega trade fair showcasing corporate gifts, stationery & promotional products.",
        image: "https://tse3.mm.bing.net/th?id=OIP.plyAa__WGIGgooigXJ5maQHaHa&pid=Api&P=0&h=180",
        date: "31 July – 2 August 2025",
        location: "Sun-n-Sand Hotel, Bund Garden Road, Pune",
        time: "11:00 AM – 7:00 PM",
        city: "Pune",
    },
    {
        title: "Runners’ Heritage Walk – Old City Pune",
        description: "Guided heritage walk exploring Pune’s historic lanes, bazaars & monuments, with local snacks included.",
        image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/07/c5/b4/bc/pune-heritage-walk.jpg?w=1200&h=-1&s=1",
        date: "20 July & 27 July 2025",
        location: "Meet at Mandai Police Chowki & Mandai Market",
        time: "7:45 AM – 11:00 AM",
        city: "Pune",
    },
    {
        title: "Heritage & Nature Walk at Sarasbaug",
        description: "Morning walk through Sarasbaug gardens to experience monsoon greenery and gain local heritage insights.",
        image: "https://tse3.mm.bing.net/th?id=OIP.TOI5t8ZUsDM_3wXY6lMUNAHaFj&pid=Api&P=0&h=180",
        date: "26 July 2025",
        location: "Sarasbaug Ganpati Temple, Saras Baug",
        time: "8:00 AM – 10:00 AM",
        city: "Pune",
    },
    {
        title: "Zero Shadow Day Observation",
        description: "Witness the Sun directly overhead—no shadows at solar noon—followed by an educational workshop at Raman Science Centre.",
        image: "https://st.adda247.com/https://s3-ap-south-1.amazonaws.com/adda247jobs-wp-assets-adda247/articles/wp-content/uploads/2023/08/18181911/Zero-Shadow-Day.jpg",
        date: "17 July 2025",
        location: "Raman Science Centre & Planetarium, Nagpur",
        time: "12:20 PM",
        city: "Nagpur",
    },
    {
        title: "Planetarium Sky Shows & Science Exhibits",
        description: "Daily astronomy shows and interactive science exhibits at the Raman Science Centre.",
        image: "https://tse2.mm.bing.net/th?id=OIP.wr63yqGrSEJp1iENigeNDwHaFJ&pid=Api&P=0&h=180",
        date: "Daily (July 2025)",
        location: "Raman Science Centre & Planetarium, Nagpur",
        time: "4:00 PM & other slots (check Centre schedule)",
        city: "Nagpur",
    },
    {
        title: "Adipuram Mahotsavam – Deepa Pooja",
        description: "Traditional Deepa Pooja ritual for women during the 18th annual Adipuram festival organized by Asthika Samaj.",
        image: "https://tse1.mm.bing.net/th?id=OIP.lPs9Cgb4aZrEzZkSbQbzrQHaD5&pid=Api&P=0&h=180",
        date: "21 July 2025",
        location: "Asthika Samaj, Nagpur",
        time: "6:30 PM (evening ritual)",
        city: "Nagpur",
    },
    {
        title: "SCZCC Tribal Art Workshop – Gond & Warli",
        description: "Hands-on painting sessions teaching indigenous Gond and Warli art traditions.",
        image: "https://tse1.mm.bing.net/th?id=OIP.Eg-9ZL67xzuG5b6rZwV3MgHaEl&pid=Api&P=0&h=180",
        date: "26 July 2025",
        location: "SCZCC (State Central Zone Cultural Centre), Nagpur",
        time: "10:00 AM – 1:00 PM",
        city: "Nagpur",
    },
    {
        title: "IJS INDIA JEWELLERY SHOW",
        description: "Exhibition of fine jewellery, gems & fashion accessories with brand stalls and live demos.",
        image: "https://tse4.mm.bing.net/th?id=OIP.2x3xflyg8K0cKT3KpNCLkAHaNK&pid=Api&P=0&h=180",
        date: "22–24 July 2025",
        location: "Mota Varachha, Surat",
        time: "11:00 AM – 8:00 PM",
        city: "Surat",
    },
    {
        title: "Gaurav Gupta Live – India Tour",
        description: "Live fashion show featuring Gaurav Gupta’s couture collection on India tour stop.",
        image: "https://cdn-az.allevents.in/events4/banners/feaba010-098b-11f0-a5c2-0f4acb0b220c-rimg-w1200-h600-dc8dffe8-gmir.jpg?v=1742915733",
        date: "26 July 2025",
        location: "Sanjeev Kumar Auditorium, Surat",
        time: "Evening (time TBC)",
        city: "Surat",
    },
    {
        title: "Surat Riverfront Night Walks",
        description: "Leisurely evening strolls along the lit-up Tapi riverfront, with food stalls & scenic views.",
        image: "https://static-blog.treebo.com/blog/wp-content/uploads/2018/07/ONGC-Bridge.jpg",
        date: "Daily, 16–31 July 2025",
        location: "Adajan Patiya, Tapi Riverfront",
        time: "6:00 PM – 9:00 PM",
        city: "Surat",
    },
    {
        title: "Science & Planetarium Shows – Surat Science Centre",
        description: "Interactive science exhibits and planetarium family shows covering astronomy, physics & tech.",
        image: "https://surattourism.in/images/places-to-visit/header/science-centre-surat-tourism-entry-fee-timings-holidays-reviews-header.jpg",
        date: "Daily, 16–31 July 2025",
        location: "Science Centre, Sarthana, Surat",
        time: "3:00 PM – 6:00 PM",
        city: "Surat",
    },
    {
        title: "Shravan Amavasya & Pind Daan Rituals",
        description: "Ancestral rites, Pind Daan and Shiva puja at the river‑banks observed on the no‑moon day of Shravan.",
        image: "https://banarastrip.com/wp-content/uploads/2023/08/Pind-Daan-rituals-Offbeat-Places-to-Visit-in-Varanasi.png",
        date: "17 July 2025",
        location: "Dashashwamedh Ghat, Varanasi",
        time: "Sunrise to noon ceremonies",
        city: "Varanasi"
    },
    {
        title: "International Temples Convention & Expo",
        description: "Convention and expo featuring temple representatives from 25 countries focusing on heritage, security and temple management.",
        image: "https://www.thestatesman.com/wp-content/uploads/2023/07/IMG_4864-1024x683.png",
        date: "22–24 July 2025",
        location: "Venue TBC, Varanasi",
        time: "10:00 AM – 6:00 PM daily",
        city: "Varanasi"
    },
    {
        title: "Ganga Aarti at Dashashwamedh Ghat",
        description: "Daily sacred Ganga Aarti ritual with lamps and chants at the main ghat.",
        image: "https://c8.alamy.com/compde/g13d0p/ganga-aarti-und-dev-deepavali-feiern-dashashwamedh-ghat-varanasi-uttar-pradesh-indien-g13d0p.jpg",
        date: "Daily, 16–31 July 2025",
        location: "Dashashwamedh Ghat, Varanasi",
        time: "7:00 PM – 7:45 PM",
        city: "Varanasi"
    },
    {    
        title: "International Conference on Engineering & Technology",
        description: "Technical conference exploring advancements in engineering and technology.",
        image: "https://www.iferp.in/blog/wp-content/uploads/2022/09/List-of-International-Conference-on-Engineering-and-Technology.jpg",
        date: "27 July 2025",
        location: "NIER / SFE venue, Madurai",
        time: "10:00 AM – 5:00 PM",
        city: "Madurai",
    },
    {
        title: "International Conference on Mathematics, Statistics & Applied Science",
        description: "Academic symposium on statistical research and applications.",
        image: "https://tse2.mm.bing.net/th?id=OIP.a_WgwlXNaYwAxL9wRM7mkQHaD4&pid=Api&P=0&h=180",
        date: "27 July 2025",
        location: "NIER / SFE venue, Madurai",
        time: "10:00 AM – 5:00 PM",
        city: "Madurai",
    },
    {
        title: "Livestock Conference – Naam Tamilar Katchi",
        description: "Conference addressing grazing rights and cattle farmers’ livelihoods.",
        image: "https://tse4.mm.bing.net/th?id=OIP.ynbFhDS8qo8b34-gK-P51QHaEK&pid=Api&P=0&h=180",
        date: "10 July 2025",
        location: "Madurai airport press zone",
        time: "Morning sessions",
        city: "Madurai",
    },
    {
        title: "Rakhi & Teej Shopping Bazaar",
        description: "Festive bazaar with clothes, gifts and décor for Rakhi and Teej.",
        image: "https://tse1.mm.bing.net/th?id=OIP.vQYVtX8vm0dU7KBW_Qn_bwHaEK&pid=Api&P=0&h=180",
        date: "24 July 2025",
        location: "Hotel Broadway Inn, Meerut",
        time: "11:00 AM – 9:00 PM",
        city: "Meerut",
    },
    {
        title: "Carnival Family Fair",
        Description: "Kids’ rides, games and family entertainment.",
        image: "https://tse1.mm.bing.net/th?id=OIP.rGrV62UxJEBuYppIDyVfcAHaEK&pid=Api&P=0&h=180",
        date: "Mid–July 2025 (e.g., 18 July)",
        location: "Carrippa Street, Meerut Cantonment",
        time: "6:00 PM – 10:00 PM",
        city: "Meerut",
    },
    {
        title: "Harsh Gujral Stand‑Up Comedy",
        description: "Live comedy show by Harsh Gujral performing his popular act.",
        image: "https://tse1.mm.bing.net/th?id=OIP.w1KiNeBDiUkwJ-3iOX3BLQHaEK&pid=Api&P=0&h=180",
        date: "July 2025 (exact date TBC)",
        location: "Meerut (venue TBC)",
        time: "6:00 PM – 7:30 PM",
        City: "Meerut",
    },
    {
        title: "Drama Workshop – Mystical Sakhi",
        description: "Performance/workshop by Keelaka Dance Company.",
        image: "https://tse1.mm.bing.net/th?id=OIP.e2mc5RzWfTzlgCI-4ekYIAHaE8&pid=Api&P=0&h=180",
        date: "16 June 2025 (ongoing series through July)",
        location: "Meerut (venue TBC)",
        time: "Evenings",
        city: "Meerut",
    },
    {
        title: "Fashionista Fashion & Lifestyle Exhibition",
        description: "Showcase of fashion, décor, jewellery in Sayaji Hotel expo.",
        image: "https://www.eventsgram.in/images/users/1675511631.jpg",
        date: "21 July 2025",
        location: "Sayaji Hotel, Raipur",
        time: "11:00 AM – 8:00 PM",
        city: "Raipur",
    },
    {
        title: "ICRIMEC Conference",
        description: "International conference on mechanical & civil engineering innovations.",
        image: "https://tse1.mm.bing.net/th?id=OIP.kv0mBqr9XRhoTrT0I1AYwQHaFb&pid=Api&P=0&h=180",
        date: "26 July 2025",
        location: "Raipur Conference Venue (Civic Center)",
        time: "10:00 AM – 5:00 PM",
        city: "Raipur",
    },
    {
        title: "Wedding Asia Expo",
        description: "Wedding services expo with planners, photography, décor vendors.",
        image: "https://tse1.mm.bing.net/th?id=OIP.FaqlG4aWPl13Jbu9YqizvwHaE7&pid=Api&P=0&h=180",
        date: "11–12 July 2025",
        location: "Courtyard By Marriott, Raipur",
        time: "11:00 AM – 7:00 PM",
        city: "Raipur",
    },
    {
        title: "Health & Beauty Trade Fair",
        description: "Trade show featuring wellness, beauty, and healthcare brands.",
        image: "https://tse2.mm.bing.net/th?id=OIP.BuoqNCfy_Nw-_OawPJK-EwHaEE&pid=Api&P=0&h=180",
        date: "11–12 July 2025",
        location: "Sayaji Hotel Exhibition Center",
        time: "11:00 AM – 7:00 PM",
        city: "Raipur",
    },
    {
        title: "India’s Most Successful Wedding & Lifestyle Rakhi Exhibition",
        description: "Premium wedding & lifestyle expo with couture, décor and accessories.",
        image: "https://tse2.mm.bing.net/th?id=OIP.KsEUh5zlRIMM-N7hTIbf4wHaD4&pid=Api&P=0&h=180",
        date: "18–19 July 2025",
        location: "Nutan Nagar Community Hall, Rajkot",
        time: "10:00 AM – 8:00 PM",
        city: "Rajkot",
    },
    {
        title: "Rakhi Special Exhibition",
        description: "Festive fashion & jewellery showcase for Rakhi shopping.",
        image: "https://c8.alamy.com/comp/2XG1WEY/happy-rakhi-festival-celebration-creative-poster-design-vector-2XG1WEY.jpg",
        date: "28–29 July 2025",
        location: "Hotel Sayaji, Kalavad Road, Rajkot",
        time: "10:00 AM – 9:00 PM",
        city: "Rajkot",
    },
    {
        title: "Premier Schools Exhibition – IIPSE",
        description: "Education fair for school admissions and resources.",
        image: "https://www.educatenepal.com/uploads/article/1358849552premier-schools-exhibition.jpg",
        date: "25–27 July 2025",
        location: "Sayaji Hotel, Rajkot",
        time: "10:00 AM – 6:00 PM",
        city: "Rajkot",
    },
    {
        title: "India Jewellery Show – Bhavnagar",
        description: "Regional jewellery showcase; reported in 25–27 July schedule.",
        image: "https://tse2.mm.bing.net/th?id=OIP.6xBAQ8Pdq3IOeKff2LD30gHaEK&pid=Api&P=0&h=180",
        date: "25–27 July 2025",
        location: "Bhavnagar (near Rajkot)",
        time: "All day",
        city: "Rajkot",
    },
    {
        title: "Creative Fashion Exhibition",
        description: "Local fashion designers showcase at Umabhavan Pushkardham.",
        image: "https://tse3.mm.bing.net/th?id=OIP.-pnyREj9lwGGqOGtMIJyJwHaE8&pid=Api&P=0&h=180",
        date: "26–27 June 2025 (runs annually)",
        location: "Umabhavan, J K Chowk, Rajkot",
        time: "Daytime sessions",
        city: "Rajkot",
    },
    {
        title: "Sustainability & Crafts Fair",
        description: "Pop-up market featuring eco-friendly crafts and local artisans.",
        image: "https://tse1.mm.bing.net/th?id=OIP.hAEltQPsFRAV6VfTC2UDXwHaHa&pid=Api&P=0&h=180",
        date: "19 July 2025",
        location: "Town Hall Plaza, Rajkot",
        time: "10:00 AM – 7:00 PM",
        city: "Rajkot",
    },
    {
        title: "Jagannathpur Rath Yatra",
        description: "Traditional chariot festival procession with eco-friendly arrangements.",
        image: "https://tse1.mm.bing.net/th?id=OIP.yVs9xlSHDRIaxM2O2DgVAgHaEK&pid=Api&P=0&h=180",
        date: "27 June – 5 July 2025",
        location: "Jagannath Temple → Mausi Bari route, Ranchi",
        time: "Daytime, major rituals midday",
        city: "Ranchi",
    },
    {
        title: "Global Visionary Award 2025 Gala",
        description: "Award ceremony for visionary leaders at Radisson Blu.",
        image: "https://tse2.mm.bing.net/th?id=OIP.I5GsmpxV4IvHpnBHRkqx5AHaEK&pid=Api&P=0&h=180",
        date: "27 July 2025",
        location: "Radisson Blu Hotel, Ranchi",
        time: "7:00 PM onwards",
        city: "Ranchi",
    },
    {
        title: "Dubai Property Expo Ranchi",
        description: "International real estate exhibition featuring Dubai projects.",
        image: "https://i0.wp.com/dubaiproperties.org.in/wp-content/uploads/2022/10/Dubai-Property-Expo-in-india.jpg?w=960&ssl=1",
        date: "18–19 July 2025",
        location: "Le Lac Sarovar Portico, Ranchi",
        time: "10:00 AM – 6:00 PM",
        city: "Ranchi",
    },
    {
        title: "AICCTU National Executive Meet",
        description: "Trade union planning meet ahead of July 9 call for strike.",
        image: "https://tse2.mm.bing.net/th?id=OIP.S4CVesIeUS_HmklE3axeFAHaD8&pid=Api&P=0&h=180",
        date: "15–16 July 2025",
        location: "Ranchi city centre venue",
        time: "All day sessions",
        city: "Ranchi",
    },
    {
        title: "Dengue Awareness Drive Launch",
        description: "Public-health campaign kickoff at municipal zones.",
        image: "https://tse2.mm.bing.net/th?id=OIP.19b5WCV6PSdV5G45w0i8sQHaHa&pid=Api&P=0&h=180",
        date: "July 2025 (early July)",
        location: "Various wards, Ranchi",
        time: "Morning sessions",
        city: "Ranchi",
    },
    {
        title: "Citywide Fair & Wedding Expo",
        description: "Local wedding & lifestyle exhibition at Radisson Blu.",
        image: "https://tse2.mm.bing.net/th?id=OIP.fxJCrMNTNjflFd4UXCXzxAHaE8&pid=Api&P=0&h=180",
        date: "1–2 July 2025",
        location: "Radisson Blu Hotel, Ranchi",
        time: "10:00 AM – 9:00 PM",
        city: "Ranchi",
    },
    {
        title: "Marketing & Startup Conference",
        description: "Training & networking event for entrepreneurs.",
        image: "https://tse3.mm.bing.net/th?id=OIP.LgHLN8Ni6WclW5GpHSjxSgHaE8&pid=Api&P=0&h=180",
        date: "TBD July 2025",
        location: "Ranchi tech park venue",
        time: "Daytime",
        city: "Ranchi",
    },
    {
        title: "International Mariyamman Temple Festival",
        description: "Annual July festival with rituals & cultural programs.",
        image: "https://media.dailythanthi.com/h-upload/2023/04/01/1212871-k-5.jpg",
        date: "July 2025 (dates vary)",
        location: "Kottai Mariyamman Temple, Salem",
        time: "All day",
        city: "Salem",
    },
    {
        title: "LPG Cylinder Dealership Seminar",
        description: "Business seminar on LPG dealership opportunities.",
        image: "https://cdn2.allevents.in/thumbs/thumb653bb1afeb40a.jpg",
        date: "24 July 2025",
        location: "Hotel Rathna Residency, Salem",
        time: "10:00 AM – 1:00 PM",
        city: "Salem",
    },
    {
        title: "Salem Summer Shopping Expo",
        description: "Community trade expo for local businesses and franchises.",
        image: "https://tse4.mm.bing.net/th?id=OIP.5zw1M-jWBQbtspMAFkLSxwHaCV&pid=Api&P=0&h=180",
        date: "5–6 July 2025",
        location: "Sri Rathnavel Jayakumar Thirumana Mandapam",
        time: "10:00 AM – 8:00 PM",
        city: "Salem",
    },
    {
        title: "Salem Sangamam Cultural Fest",
        description: "Cultural showcasing of Tamil arts—dance, music, theatre.",
        image: "https://tse4.mm.bing.net/th?id=OIP.IDZn0tsSbKEmXsrNMby5XAHaEH&pid=Api&P=0&h=180",
        date: "June–July 2025",
        location: "City cultural centre, Salem",
        time: "Evening programs",
        city: "Salem",
    },
    {
        title: "Psychic Fair at Masonic Temple",
        description: "Esoteric fair featuring readings and workshops.",
        image: "https://tse1.mm.bing.net/th?id=OIP.IVv47sNgpZivBLfYUkI5PAHaIO&pid=Api&P=0&h=180",
        date: "19 July 2025",
        location: "Salem Masonic Temple",
        time: "11:00 AM – 5:00 PM",
        city: "Salem",
    },
    {
        title: "Live Jazz Night",
        description: "Live jazz music performance at local venue.",
        image: "https://tse1.mm.bing.net/th?id=OIP.1-ebXO3WYYQx569hWAp6BgHaE8&pid=Api&P=0&h=180",
        date: "29 July 2025",
        location: "East Regiment Lounge, Salem",
        time: "7:00 PM – 9:00 PM",
        city: "Salem",
    },
    {
        title: "After Hours on the Roof",
        description: "Rooftop social evening at Hotel Salem.",
        image: "https://tse2.mm.bing.net/th?id=OIP.hFbvEIW3QV5VIR2jlBu45gHaEK&pid=Api&P=0&h=180",
        date: "16 July 2025",
        location: "Hotel Salem Rooftop",
        time: "8:00 PM onwards",
        city: "Salem",
    },
    {
        title: "Twilight Stomp 2025",
        description: "Cultural dance & art festival with competitions and performances.",
        image: "https://api.semmelcloud.de/api/file/mediumOptimized/80613_stomp-2025-sc_highl_art_square.webp",
        date: "20 July 2025",
        location: "Morais City, West Thillai Nagar, Tiruchirappalli",
        time: "9:00 AM – 10:00 PM",
        city: "Tiruchirappalli",
    },
    {
        title: "Kids’ Junior Thon Run",
        description: "Children’s running event (LKG–5th), medals and tshirts provided.",
        image: "https://tse4.mm.bing.net/th?id=OIP.EhMDfIEzQ0B9CCEOTzggrQHaEz&pid=Api&P=0&h=180",
        date: "13 July 2025",
        location: "Anna Stadium, Tiruchirappalli",
        time: "7:00 AM – 2:00 PM",
        city: "Tiruchirappalli",
    },
    {
        title: "Build Material & Furniture Expo",
        description: "Tradeshow showcasing building supplies and furniture.",
        image: "https://tse4.mm.bing.net/th?id=OIP.4kUsdZJVxpY9d2oYUqYgrgHaDt&pid=Api&P=0&h=180",
        date: "July 2025 (exact date TBC)",
        location: "Civil Engineers’ Association venue, Tiruchirappalli",
        time: "10:00 AM – 6:00 PM",
        city: "Tiruchirappalli",
    },
    {
        title: "Robotics & AI Conference",
        description: "Technical conference on robotics and safety engineering.",
        image: "https://tse3.mm.bing.net/th?id=OIP.-mtyGvcXH9bT6RxADb99ygHaEO&pid=Api&P=0&h=180",
        date: "13 July 2025",
        location: "NIER / College venue, Tiruchirappalli",
        time: "9:00 AM – 5:00 PM",
        city: "Tiruchirappalli",
    },
    {
        title: "Educational Symposium & Workshops",
        description: "Series of academic workshops across disciplines.",
        image: "https://tse3.mm.bing.net/th?id=OIP.fsxdcZww76JNbiQpqUPMjwHaDn&pid=Api&P=0&h=180",
        date: "July 2025 (ongoing)",
        location: "Saranathan College, Tiruchirappalli",
        time: "10:00 AM – 4:00 PM",
        city: "Tiruchirappalli",
    },
    {
        title: "Cultural Temple Festival Events",
        description: "Local musical and dance offerings at temples.",
        image: "https://tse1.mm.bing.net/th?id=OIP.mtTsdke6dUq1KJuAuONc5QHaDV&pid=Api&P=0&h=180",
        date: "July 2025 (temple schedule)",
        location: "Local temples across Trichy",
        time: "Evening rituals",
        city: "Tiruchirappalli",
    },
    {
        title: "Startup & Tech Meetup",
        description: "Casual meetup of local tech entrepreneurs.",
        image: "https://tse1.mm.bing.net/th?id=OIP.graTfMP7FuD5FAOyxs_SggHaE8&pid=Api&P=0&h=180",
        date: "Late July 2025 (TBC)",
        location: "Trichy tech hub/co‑working space",
        time: "6:00 PM – 8:00 PM",
        city: "Tiruchirappalli",
    }
]

module.exports={localData:localCity};